project:
  type: website

website:
  title: "Chenghuiyu Fan's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cfan0055
format:
  html:
    theme: cosmo
    css: styles.css



